"use strict";
exports.__esModule = true;
var Strack_1 = require("./Strack");
var strack = new Strack_1.Stack();
console.log(strack);
strack.push(10);
console.log(strack);
console.log(strack.size());
strack.push(20);
strack.push(30);
strack.push(30);
console.log(strack);
console.log(strack.size());
strack.push(40);
console.log(strack);
console.log(strack.size());
strack.pop();
console.log(strack);
console.log(strack.size());
